-- VACIADO DE TABLAS

DELETE FROM RUTA_HORARIO;
DELETE FROM HORARIO;
DELETE FROM RUTA_TIPO_BUS;
DELETE FROM RUTA;
DELETE FROM PLATAFORMA;
DELETE FROM PORTAL;
DELETE FROM TRONCAL;
DELETE FROM EMPRESA_OPERADORA;
DELETE FROM ESTACION;
DELETE FROM VAGON;
DELETE FROM PARADAS_RUTAS;

-- REINICIALIZAR AUTO_INCREMENTS

ALTER TABLE RUTA_HORARIO AUTO_INCREMENT = 1;
ALTER TABLE HORARIO AUTO_INCREMENT = 1;
ALTER TABLE RUTA_TIPO_BUS AUTO_INCREMENT = 1;
ALTER TABLE RUTA AUTO_INCREMENT = 1;
ALTER TABLE PLATAFORMA AUTO_INCREMENT = 1;
ALTER TABLE PORTAL AUTO_INCREMENT = 1;
ALTER TABLE TRONCAL AUTO_INCREMENT = 1;
ALTER TABLE EMPRESA_OPERADORA AUTO_INCREMENT = 1;
ALTER TABLE ESTACION AUTO_INCREMENT = 1;
ALTER TABLE VAGON AUTO_INCREMENT = 1;
ALTER TABLE PARADAS_RUTAS AUTO_INCREMENT = 1;

-- ELIMINACIÓN DE TABLAS

DROP TABLE RUTA_HORARIO CASCADE;
DROP TABLE HORARIO CASCADE;
DROP TABLE RUTA_TIPO_BUS CASCADE;
DROP TABLE PARADAS_RUTAS CASCADE;
DROP TABLE VAGON CASCADE;
DROP TABLE RUTA CASCADE;
DROP TABLE PLATAFORMA CASCADE;
DROP TABLE EMPRESA_OPERADORA CASCADE;
DROP TABLE ESTACION CASCADE;
DROP TABLE TRONCAL CASCADE;
DROP TABLE PORTAL CASCADE;
DROP TABLE TIPO_BUS CASCADE;

-- ELIMINACIÓN DE LA BASE DE DATOS

DROP DATABASE transmilenio;